### ISSUE TITLE
Expose default port in Dockerfile

### ISSUE THREAD

**Issue by kekonn** [Wakeful-Cloud/yarr#34]
I know I can override the port through env and bindings, but I use Traefik. With Traefik I don't have to bind any internal port to outside port if the port is defined in the dockerfile.

[It automatically detects the internal port](https://doc.traefik.io/traefik/providers/docker/#port-detection) (when exposed) and routes traffic through it through the Docker vnets. If you agree, I will create a pull request for it.

**Comment by Wakeful-Cloud** [comment]
Apologies for the delay - yes, please open a PR to add the appropriate `EXPOSE 7070/tcp` directive.
